name: 'Pull Request Artifact'
description: 'Post build artifacts in comments to pull request'
author: 'Donovan Hiland'
inputs:
  token:
    description: 'Token for current repo (used to post PR comment)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
